version: '3.8'
services:
  api:
    container_name: api-container
    restart: always
    build: ./server
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "6969:6969"
    depends_on:
      - db
  client:
    container_name: client-container
    restart: always
    build: ./website
    ports:
      - "8080:8080"
    depends_on:
      - api
  db:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/db